-- Migration: Create web_generator table
-- Created: 2025-08-11

CREATE TABLE IF NOT EXISTS public.web_generator (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  owner text NOT NULL,
  project_name text NOT NULL,
  project_id text NOT NULL,
  chat_id text NOT NULL,
  CONSTRAINT web_generator_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_web_generator_owner ON public.web_generator(owner);
CREATE INDEX IF NOT EXISTS idx_web_generator_project_id ON public.web_generator(project_id);
CREATE INDEX IF NOT EXISTS idx_web_generator_chat_id ON public.web_generator(chat_id);
CREATE INDEX IF NOT EXISTS idx_web_generator_created_at ON public.web_generator(created_at);

-- Add comments for documentation
COMMENT ON TABLE public.web_generator IS 'Stores web generator project information';
COMMENT ON COLUMN public.web_generator.id IS 'Auto-generated primary key';
COMMENT ON COLUMN public.web_generator.created_at IS 'Timestamp when the record was created';
COMMENT ON COLUMN public.web_generator.owner IS 'Owner/username of the project';
COMMENT ON COLUMN public.web_generator.project_name IS 'Name of the generated project';
COMMENT ON COLUMN public.web_generator.project_id IS 'External project ID from v0 service';
COMMENT ON COLUMN public.web_generator.chat_id IS 'Associated chat/conversation ID';
